# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Andor_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import*

import numpy as np
from PyQt5.QtCore import (QCoreApplication, QMetaObject, QRect,Qt)
from PyQt5.QtGui import (QFont)
from PyQt5.QtWidgets import ( QDoubleSpinBox, QGridLayout, QLCDNumber, QLabel, QMenuBar,
QProgressBar, QPushButton, QSizePolicy, QSpinBox, QStatusBar, QWidget)
import matplotlib.figure as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT
import pyqtgraph as pg




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1560, 1069)
        MainWindow.setAutoFillBackground(True)
        #MainWindow.setStyleSheet("background-color: grey;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Acquire =QPushButton(self.centralwidget)
        self.Acquire.setGeometry(QRect(10, 140, 89, 25))
        self.Acquire.setObjectName("Acquire")

        self.Stop = QPushButton(self.centralwidget)
        self.Stop.setGeometry(QRect(110, 140, 89, 25))
        self.Stop.setObjectName("Stop")

        self.fileloc = QLineEdit(self.centralwidget)
        self.fileloc.setObjectName(u"SaveLoc")
        self.fileloc.setGeometry(QRect(60, 500,161, 25))
        self.fileloc.setText("Default")

        self.Save = QPushButton(self.centralwidget)
        self.Save.setObjectName(u"Save")
        self.Save.setGeometry(QRect(60, 460, 89, 25))

        self.isMilling = QCheckBox(self.centralwidget)
        self.isMilling.setObjectName(u"isMilling")
        self.isMilling.setGeometry(QRect(80, 540, 100, 25))

        self.TopDown = QRadioButton(self.centralwidget)
        self.TopDown.setObjectName(u"TopDown")
        self.TopDown.setGeometry(QRect(25, 570, 100, 25))


        self.BottomUp = QRadioButton(self.centralwidget)
        self.BottomUp.setObjectName(u"BottomUp")
        self.BottomUp.setGeometry(QRect(120, 570, 100, 25))


        self.Bins = QSpinBox(self.centralwidget)
        self.Bins.setGeometry(QRect(180, 210, 48, 26))
        self.Bins.setMinimum(1)
        self.Bins.setProperty("value", 1)
        self.Bins.setObjectName("Bins")

        self.Frames = QSpinBox(self.centralwidget)
        self.Frames.setGeometry(QRect(110, 210, 48, 26))
        self.Frames.setMinimum(1)
        self.Frames.setProperty("value", 1)
        self.Frames.setObjectName("Frames")

        self.BinLb = QLabel(self.centralwidget)
        self.BinLb.setGeometry(QRect(180, 180, 91, 31))
        self.BinLb.setObjectName("BinLb")

        self.Framelb = QLabel(self.centralwidget)
        self.Framelb.setGeometry(QRect(110, 180, 91, 31))
        self.Framelb.setObjectName("Framelb")

        self.IntTime = QDoubleSpinBox(self.centralwidget)
        self.IntTime.setGeometry(QRect(10, 210, 69, 26))
        self.IntTime.setMaximum(20.0)
        self.IntTime.setMinimum(0.001)
        self.IntTime.setDecimals(3)
        self.IntTime.setSingleStep(0.1)
        self.IntTime.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.IntTime.setObjectName("IntTime")

        self.IntTimeLb = QLabel(self.centralwidget)
        self.IntTimeLb.setGeometry(QRect(10, 180, 91, 31))
        self.IntTimeLb.setObjectName("IntTimeLb")

        self.Disconnect = QPushButton(self.centralwidget)
        self.Disconnect.setGeometry(QRect(110, 70, 89, 25))
        self.Disconnect.setObjectName("Disconnect")

        self.Connect = QPushButton(self.centralwidget)
        self.Connect.setGeometry(QRect(10, 70, 89, 25))
        self.Connect.setObjectName("Connect")

        self.Res = QLCDNumber(self.centralwidget)
        self.Res.setGeometry(QRect(40, 390, 150, 35))
        font = QFont()
        font.setPointSize(11)
        self.Res.setFont(font)
        self.Res.setAutoFillBackground(False)
        self.Res.setSmallDecimalPoint(True)
        self.Res.setObjectName("Resolution")

        self.ResLb = QLabel(self.centralwidget)
        self.ResLb.setGeometry(QRect(40, 360, 141, 31))
        font = QFont()
        font.setPointSize(16)
        self.ResLb.setFont(font)
        self.ResLb.setObjectName("ResLb")

        self.Laser385 = QCheckBox(self.centralwidget)
        self.Laser385.setGeometry(QRect(160, 750, 92, 23))
        font = QFont()
        font.setPointSize(13)
        self.Laser385.setFont(font)
        self.Laser385.setObjectName("Laser385")

        self.Laser_HubLb = QLabel(self.centralwidget)
        self.Laser_HubLb.setGeometry(QRect(240, 710, 141, 31))
        font = QFont()
        font.setPointSize(18)
        self.Laser_HubLb.setFont(font)
        self.Laser_HubLb.setObjectName("Laser_HubLb")

        self.Laser470 = QCheckBox(self.centralwidget)
        self.Laser470.setGeometry(QRect(250, 750, 92, 23))
        font = QFont()
        font.setPointSize(13)
        self.Laser470.setFont(font)
        self.Laser470.setObjectName("Laser470")

        self.Laser555 = QCheckBox(self.centralwidget)
        self.Laser555.setGeometry(QRect(340, 750, 92, 23))
        font = QFont()
        font.setPointSize(13)
        self.Laser555.setFont(font)
        self.Laser555.setObjectName("Laser555")

        self.Laser625 = QCheckBox(self.centralwidget)
        self.Laser625.setGeometry(QRect(430, 750, 92, 23))
        font = QFont()
        font.setPointSize(13)
        self.Laser625.setFont(font)
        self.Laser625.setObjectName("Laser625")

        self.PwSlider_385 = QSlider(self.centralwidget)
        self.PwSlider_385.setGeometry(QRect(180, 810, 41, 211))
        self.PwSlider_385.setOrientation(Qt.Vertical)
        self.PwSlider_385.setObjectName("PwSlider_385")

        self.PowerNumber385 = QLCDNumber(self.centralwidget)
        self.PowerNumber385.setGeometry(QRect(160, 770, 91, 41))
        self.PowerNumber385.setObjectName("PowerNumber385")

        self.Laser_HubLb_2 = QLabel(self.centralwidget)
        self.Laser_HubLb_2.setGeometry(QRect(0, 770, 151, 31))
        font = QFont()
        font.setPointSize(13)
        self.Laser_HubLb_2.setFont(font)
        self.Laser_HubLb_2.setObjectName("Laser_HubLb_2")

        self.PowerNumber470 = QLCDNumber(self.centralwidget)
        self.PowerNumber470.setGeometry(QRect(250, 770, 91, 41))
        self.PowerNumber470.setObjectName("PowerNumber470")

        self.PwSlider_470 = QSlider(self.centralwidget)
        self.PwSlider_470.setGeometry(QRect(270, 810, 41, 211))
        self.PwSlider_470.setOrientation(Qt.Vertical)
        self.PwSlider_470.setObjectName("PwSlider_470")
        self.PwSlider_470.setMaximum(52)

        self.PowerNumber_555 = QLCDNumber(self.centralwidget)
        self.PowerNumber_555.setGeometry(QRect(340, 770, 91, 41))
        self.PowerNumber_555.setObjectName("PowerNumber_555")

        self.PwSlider_625 = QSlider(self.centralwidget)
        self.PwSlider_625.setGeometry(QRect(450, 810, 41, 211))
        self.PwSlider_625.setOrientation(Qt.Vertical)
        self.PwSlider_625.setObjectName("PwSlider_625")

        self.PowerNumber_625 = QLCDNumber(self.centralwidget)
        self.PowerNumber_625.setGeometry(QRect(430, 770, 91, 41))
        self.PowerNumber_625.setObjectName("PowerNumber_625")

        self.PwSlider_555 = QSlider(self.centralwidget)
        self.PwSlider_555.setGeometry(QRect(360, 810, 41, 211))
        self.PwSlider_555.setOrientation(Qt.Vertical)
        self.PwSlider_555.setObjectName("PwSlider_555")
        self.PwSlider_555.setMaximum(85)

        self.LaserOn = QPushButton(self.centralwidget)
        self.LaserOn.setGeometry(QRect(380, 720, 41, 25))
        self.LaserOn.setObjectName("LaserOn")

        self.LaserOff = QPushButton(self.centralwidget)
        self.LaserOff.setGeometry(QRect(420, 720, 41, 25))
        self.LaserOff.setObjectName("LaserOff")

        self.PowerNumberAc385 = QLCDNumber(self.centralwidget)
        self.PowerNumberAc385.setGeometry(QRect(140,900, 51, 51))
        self.PowerNumberAc385.setObjectName("PowerNumberAc385")

        self.PowerNumberAc470 = QLCDNumber(self.centralwidget)
        self.PowerNumberAc470.setGeometry(QRect(230,900, 51, 51))
        self.PowerNumberAc470.setObjectName("PowerNumberAc470")

        self.PowerNumberAc555 = QLCDNumber(self.centralwidget)
        self.PowerNumberAc555.setGeometry(QRect(320, 900, 51, 51))
        self.PowerNumberAc555.setObjectName("PowerNumberAc555")

        self.PowerNumberAc625 = QLCDNumber(self.centralwidget)
        self.PowerNumberAc625.setGeometry(QRect(410, 900, 51, 51))
        self.PowerNumberAc625.setObjectName("PowerNumberAc625")

        self.Filters = QComboBox(self.centralwidget)
        self.Filters.setGeometry(QRect(570, 750, 121, 25))
        self.Filters.setObjectName("comboBox")
        self.Filters.addItem("")
        self.Filters.addItem("")
        self.Filters.addItem("")
        self.Filters.addItem("")
        self.Filters.addItem("")

        self.Laser_HubLb_3 = QLabel(self.centralwidget)
        self.Laser_HubLb_3.setGeometry(QRect(560, 710, 141, 31))
        font = QFont()
        font.setPointSize(18)
        self.Laser_HubLb_3.setFont(font)
        self.Laser_HubLb_3.setObjectName("Laser_HubLb_3")

        self.Cont = QCheckBox(self.centralwidget)
        self.Cont.setGeometry(QRect(5, 250, 131, 23))
        self.Cont.setObjectName("Laser385_2")

        self.savecheck = QCheckBox(self.centralwidget)
        self.savecheck.setGeometry(QRect(110, 250, 92, 23))
        self.savecheck.setObjectName("savecheck")

        self.StageMovementLb = QLabel(self.centralwidget)
        self.StageMovementLb.setGeometry(QRect(800, 700, 101, 31))
        font = QFont()
        font.setPointSize(18)
        self.StageMovementLb.setFont(font)
        self.StageMovementLb.setObjectName("StageMovementLb")

        self.NegX = QPushButton(self.centralwidget)
        self.NegX.setGeometry(QRect(710, 820, 90, 80))
        font = QFont()
        font.setPointSize(30)
        self.NegX.setFont(font)
        self.NegX.setObjectName("NegX")

        self.PosX = QPushButton(self.centralwidget)
        self.PosX.setGeometry(QRect(880, 820, 90, 80))
        font = QFont()
        font.setPointSize(30)
        self.PosX.setFont(font)
        self.PosX.setObjectName("PosX")

        self.PosY = QPushButton(self.centralwidget)
        self.PosY.setGeometry(QRect(800, 730, 80, 90))
        font = QFont()
        font.setPointSize(30)
        self.PosY.setFont(font)
        self.PosY.setObjectName("PosY")

        self.NegY = QPushButton(self.centralwidget)
        self.NegY.setGeometry(QRect(800, 900, 80, 90))
        font = QFont()
        font.setPointSize(30)
        self.NegY.setFont(font)
        self.NegY.setObjectName("NegY")

        self.PosFocus = QPushButton(self.centralwidget)
        self.PosFocus.setGeometry(QRect(1000, 750, 90, 80))
        font = QFont()
        font.setPointSize(30)
        self.PosFocus.setFont(font)
        self.PosFocus.setObjectName("PosFocus")

        self.NegFocus = QPushButton(self.centralwidget)
        self.NegFocus.setGeometry(QRect(1000, 830, 90, 80))

        font = QFont()
        font.setPointSize(30)
        self.NegFocus.setFont(font)
        self.NegFocus.setObjectName("NegFocus")

        self.StageMovementLb_2 = QLabel(self.centralwidget)
        self.StageMovementLb_2.setGeometry(QRect(1000, 700, 101, 31))

        font = QFont()
        font.setPointSize(18)
        self.StageMovementLb_2.setFont(font)
        self.StageMovementLb_2.setObjectName("StageMovementLb_2")

        self.StepSize = QSlider(self.centralwidget)
        self.StepSize.setGeometry(QRect(590, 990, 501, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StepSize.sizePolicy().hasHeightForWidth())
        self.StepSize.setSizePolicy(sizePolicy)
        self.StepSize.setMaximum(10000)
        self.StepSize.setSingleStep(1)
        self.StepSize.setOrientation(Qt.Horizontal)
        self.StepSize.setInvertedControls(False)
        self.StepSize.setTickPosition(QSlider.TicksAbove)
        self.StepSize.setObjectName("StepSize")

        self.StepSizeInd = QLCDNumber(self.centralwidget)
        self.StepSizeInd.setGeometry(QRect(580, 922, 191, 51))
        self.StepSizeInd.setObjectName("StepSizeInd")

        self.StageMovementLb_3 = QLabel(self.centralwidget)
        self.StageMovementLb_3.setGeometry(QRect(590, 930, 101, 31))

        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.StageMovementLb_3.setFont(font)
        self.StageMovementLb_3.setObjectName("StageMovementLb_3")

        self.AccProgg = QProgressBar(self.centralwidget)
        self.AccProgg.setGeometry(QRect(10, 310, 231, 23))
        self.AccProgg.setProperty("value", 24)
        self.AccProgg.setObjectName("AccProgg")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 1178, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        #Set up Layout Wigdet with 4 main graphs
        self.TotGraphWidg = QWidget(self.centralwidget)
        self.TotGraphWidg.setGeometry(QRect(250, 0, 1400, 700))
        self.TotGraphWidg.setObjectName("TotGraphwidget")
        #Child og Grid widget
        self.TotGraphs = QGridLayout(self.TotGraphWidg)
        self.TotGraphs.setContentsMargins(0, 0, 0, 0)
        self.TotGraphs.setSpacing(2)
        self.TotGraphs.setObjectName("TotGraphs")


        #Subcolumn layout for left grid side
        self.Graphs_1 = QVBoxLayout()
        self.Graphs_1.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.Graphs_1.setContentsMargins(0, -1, -1, -1)
        self.Graphs_1.setSpacing(0)
        self.Graphs_1.setObjectName("Graphs_1")

        self.img = pg.ImageItem()
        self.Hist = pg.HistogramLUTWidget(self.TotGraphWidg, orientation='horizontal')
        self.Hist.setObjectName(u"Hist")
        self.Hist.setImageItem(self.img)
        self.Hist.vb.setMouseEnabled(y=False)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        self.Hist.setSizePolicy(sizePolicy)
        self.Hist.setAutoFillBackground(True)

        self.Image_Plot = pg.PlotWidget(self.TotGraphWidg)
        self.Image_Plot.setObjectName(u"Image")
        self.Image_Plot.setAutoFillBackground(True)
        self.Image_Plot.addItem(self.img)


        self.Graphs_1.addWidget(self.Image_Plot)
        self.Graphs_1.addWidget(self.Hist)
        self.Graphs_1.setStretch(0, 4)
        self.Graphs_1.setStretch(1, 1)
        #add to total layout
        self.TotGraphs.addLayout(self.Graphs_1, 0, 0, 1, 1)

        #Subcolumn layout for right grid side
        self.Graphs_2 =  QVBoxLayout()
        self.Graphs_2.setSpacing(0)
        self.Graphs_2.setObjectName(u"Graphs_2")


        self.AlgFitting = pg.PlotWidget(self.TotGraphWidg)
        self.AlgFitting.setObjectName(u"ROI")
        self.AlgFitting.setAutoFillBackground(True)

        self.ROIGraph = pg.PlotWidget(self.centralwidget)
        self.ROIGraph.setGeometry(QRect(1100, 680, 1000, 680))
        self.ROIGraph.setObjectName("PSF_Fitting")

        self.Graphs_2.addWidget(self.AlgFitting)
        self.Graphs_2.addWidget(self.ROIGraph)
        self.Graphs_2.setStretch(0, 4)
        self.Graphs_2.setStretch(1, 1)

        self.TotGraphs.addLayout(self.Graphs_2, 0, 1, 1, 1)
        self.TotGraphs.setColumnMinimumWidth(0, 1)
        self.TotGraphs.setColumnMinimumWidth(1, 2)

        # Custom ROI for selecting an image region
        self.roi = pg.ROI([10, 14], [500, 500])
        self.roi.addScaleHandle([0.5, 1], [0.5, 0.5])
        self.roi.addScaleHandle([1, 0.5], [0.5, 0.5])
        self.roi.addScaleHandle([1, 1], [0.5, 0.5])
        self.roi.addRotateHandle([-0.5, 1], [0.5, 0.5])
        pen = pg.mkPen(cosmetic=False, width=.01, color='r')
        self.roi.setPen(pen)
        # adding roi to the plot area
        self.Image_Plot.addItem(self.roi)
        # setting z value to roi
        # making sure ROI is drawn above image
        self.roi.setZValue(10)





        self.data = np.random.normal(size=(1000, 1000))
        self.data[20:800, 20:800] += 2.

        # setting gaussian filter to the data
        self.data = pg.gaussianFilter(self.data, (3, 3))
        self.data += np.random.normal(size=(1000, 1000)) * 0.1
        self.img.setImage(self.data)
        self.Clear = QPushButton(self.centralwidget)
        self.Clear.setObjectName(u"Clear")
        self.Clear.setGeometry(QRect(1700, 10, 100, 25))

        self.Begin_Fit = QCheckBox(self.centralwidget)
        self.Begin_Fit.setObjectName(u"Begin_Fit")
        self.Begin_Fit.setGeometry(QRect(1700, 60, 100, 25))

        self.Reset_Fit = QCheckBox(self.centralwidget)
        self.Reset_Fit.setObjectName(u"Reset_Fit")
        self.Reset_Fit.setGeometry(QRect(1700, 80, 100, 25))



        self.Mill_Goal = QLCDNumber(self.centralwidget)
        self.Mill_Goal.setGeometry(QRect(1700, 100, 81, 31))
        self.Mill_Goal.setObjectName("Mill_Goal")

        self.AYlmLb = QLabel(self.centralwidget)
        self.AYlmLb.setGeometry(QRect(1700, 130, 61, 20))
        self.AYlmLb.setObjectName("AYlmLb")
        self.Alg_YLim = QDoubleSpinBox(self.centralwidget)
        self.Alg_YLim.setObjectName(u"Alg_YLim")
        self.Alg_YLim.setGeometry(QRect(1700, 150, 100, 25))
        self.Alg_YLim.setValue(30)
        self.Alg_YLim.setMaximum(5000)


        self.AYMinlmLb = QLabel(self.centralwidget)
        self.AYMinlmLb.setGeometry(QRect(1700, 170, 61, 20))
        self.AYMinlmLb.setObjectName("AYMinlmLb")
        self.Alg_YLimMin = QDoubleSpinBox(self.centralwidget)
        self.Alg_YLimMin.setObjectName(u"Alg_YLimMin")
        self.Alg_YLimMin.setGeometry(QRect(1700, 190, 100, 25))
        self.Alg_YLimMin.setValue(0)
        self.Alg_YLimMin.setMaximum(5000)


        self.Wavelb = QLabel(self.centralwidget)
        self.Wavelb.setGeometry(QRect(10, 1020, 61, 20))
        self.Wavelb.setObjectName("Wavelb")

        self.Wave = QDoubleSpinBox(self.centralwidget)
        self.Wave.setGeometry(QRect(70, 1020, 71, 22))
        self.Wave.setMaximum(5000000.0)
        self.Wave.setObjectName("Wave")
        self.Wave.setValue(532)

        self.YSize = QDoubleSpinBox(self.centralwidget)
        self.YSize.setGeometry(QRect(220, 1020, 71, 22))
        self.YSize.setMaximum(5000000.0)
        self.YSize.setObjectName("YSize")
        self.YSize.setValue(1)

        self.MillTime = QDoubleSpinBox(self.centralwidget)
        self.MillTime.setGeometry(QRect(370, 1020, 71, 22))
        self.MillTime.setMaximum(5000000.0)
        self.MillTime.setValue(1)
        self.MillTime.setObjectName("MillTime")

        self.YsizeLb = QLabel(self.centralwidget)
        self.YsizeLb.setGeometry(QRect(150, 1020, 61, 20))
        self.YsizeLb.setObjectName("YsizeLb")

        self.Time_lb = QLabel(self.centralwidget)
        self.Time_lb.setGeometry(QRect(300, 1020, 61, 20))
        self.Time_lb.setObjectName("Time_lb")

        self.MillingRate_LCD = QLCDNumber(self.centralwidget)
        self.MillingRate_LCD.setGeometry(QRect(190, 1060, 81, 31))
        self.MillingRate_LCD.setObjectName("MillingRate_LCD")

        self.Milling_lb = QLabel(self.centralwidget)
        self.Milling_lb.setGeometry(QRect(190, 1040, 101, 20))
        self.Milling_lb.setObjectName("Milling_lb")

        self.ExpFreq_LCD = QLCDNumber(self.centralwidget)
        self.ExpFreq_LCD.setGeometry(QRect(300, 1060, 81, 31))
        self.ExpFreq_LCD.setObjectName("ExpFreq_LCD")

        self.ExpFreq_lb = QLabel(self.centralwidget)
        self.ExpFreq_lb.setGeometry(QRect(300, 1040, 101, 20))
        self.ExpFreq_lb.setObjectName("ExpFreq_lb")

        self.GaussFit_lb = QLabel(self.centralwidget)
        self.GaussFit_lb.setGeometry(QRect(190, 1100, 151, 20))
        font = QFont()
        font.setPointSize(18)
        self.GaussFit_lb.setFont(font)
        self.GaussFit_lb.setObjectName("GaussFit_lb")

        self.Gauss_A = QDoubleSpinBox(self.centralwidget)
        self.Gauss_A.setGeometry(QRect(50, 1130, 71, 22))
        self.Gauss_A.setMaximum(5000000.0)
        self.Gauss_A.setObjectName("Gauss_A")
        self.Gauss_A.setValue(50)

        self.GaussSig_X = QDoubleSpinBox(self.centralwidget)
        self.GaussSig_X.setGeometry(QRect(190, 1130, 71, 22))
        self.GaussSig_X.setMaximum(5000000.0)
        self.GaussSig_X.setObjectName("GaussSig_X")
        self.GaussSig_X.setValue(2)

        self.sigmaX_lb = QLabel(self.centralwidget)
        self.sigmaX_lb.setGeometry(QRect(130, 1130, 61, 20))
        self.sigmaX_lb.setObjectName("sigmaX_lb")

        self.A_lb = QLabel(self.centralwidget)
        self.A_lb.setGeometry(QRect(20, 1130, 21, 20))
        self.A_lb.setObjectName("A_lb")

        self.Gauss_X0 = QDoubleSpinBox(self.centralwidget)
        self.Gauss_X0.setGeometry(QRect(290, 1130, 71, 22))
        self.Gauss_X0.setMaximum(5000000.0)
        self.Gauss_X0.setObjectName("Gauss_X0")
        self.Gauss_X0.setValue(3)

        self.X0_lb = QLabel(self.centralwidget)
        self.X0_lb.setGeometry(QRect(270, 1130, 61, 20))
        self.X0_lb.setObjectName("X0_lb")

        self.Gauss_Y0 = QDoubleSpinBox(self.centralwidget)
        self.Gauss_Y0.setGeometry(QRect(390, 1130, 71, 22))
        self.Gauss_Y0.setMaximum(5000000.0)
        self.Gauss_Y0.setObjectName("Gauss_Y0")
        self.Gauss_Y0.setValue(3)

        self.Y0_lb = QLabel(self.centralwidget)
        self.Y0_lb.setGeometry(QRect(370, 1130, 41, 20))
        self.Y0_lb.setObjectName("Y0_lb")

        self.C_lb = QLabel(self.centralwidget)
        self.C_lb.setGeometry(QRect(470, 1130, 61, 20))
        self.C_lb.setObjectName("C_lb")

        self.Gauss_C = QDoubleSpinBox(self.centralwidget)
        self.Gauss_C.setGeometry(QRect(490, 1130, 71, 22))
        self.Gauss_C.setMaximum(5000000.0)
        self.Gauss_C.setObjectName("Gauss_C")
        self.Gauss_C.setValue(50)

        self.Fit_Button = QPushButton(self.centralwidget)
        self.Fit_Button.setGeometry(QRect(400, 1090, 71, 21))
        self.Fit_Button.setObjectName("Fit_Button")

        self.PSFFit = pg.PlotWidget(self.centralwidget)
        self.PSFFit.setBackground("w")
        self.PSFFit.setGeometry(QRect(570, 1020, 500, 130))
        self.PSFFit.setObjectName("PSFFit")

        self.PSF_X_Y = QCheckBox(self.centralwidget)
        self.PSF_X_Y.setGeometry(QRect(500, 1090, 80, 20))
        self.PSF_X_Y.setObjectName('PSF_X_Y')

        self.PSFFitting = pg.ImageView(self.centralwidget)
        self.PSFFitting.setGeometry(QRect(1100, 710, 800, 440))
        self.PSFFitting.setObjectName("AlgFitting")


        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Andor Camera"))
        self.Acquire.setText(_translate("MainWindow", "Acquire"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.Framelb.setText(_translate("MainWindow", "Frames"))
        self.BinLb.setText(_translate("MainWindow", "Bins"))
        self.IntTimeLb.setText(_translate("MainWindow", "Exp Time (s)"))
        self.Disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.ResLb.setText(_translate("MainWindow", "Resolution"))
        self.isMilling.setText(_translate("MainWindow", "Is Milling"))
        self.TopDown.setText(_translate("MainWindow", "Top Down"))
        self.BottomUp.setText(_translate("MainWindow", "Bottom Up"))
        self.Laser385.setText(_translate("MainWindow", "385 nm"))
        self.Laser_HubLb.setText(_translate("MainWindow", "Laser Hub"))
        self.Laser470.setText(_translate("MainWindow", "470 nm"))
        self.Laser555.setText(_translate("MainWindow", "555 nm"))
        self.savecheck.setText(_translate("MainWindow", "Save Run?"))
        self.Laser625.setText(_translate("MainWindow", "625 nm"))
        self.Laser_HubLb_2.setText(_translate("MainWindow", "Laser Power (mw)"))
        self.LaserOn.setText(_translate("MainWindow", "On"))
        self.LaserOff.setText(_translate("MainWindow", "Off"))
        self.Filters.setItemText(0, _translate("MainWindow", "Pass-Through"))
        self.Filters.setItemText(1, _translate("MainWindow", "431 ± 36 nm LP"))
        self.Filters.setItemText(2, _translate("MainWindow", "514 ± 30 nm LP"))
        self.Filters.setItemText(3, _translate("MainWindow", "595 ± 30 nm LP"))
        self.Filters.setItemText(4, _translate("MainWindow", "698 ± 90 nm LP"))
        self.Laser_HubLb_3.setText(_translate("MainWindow", "Laser Filter"))
        self.Cont.setText(_translate("MainWindow", "Continuous"))
        self.StageMovementLb.setText(_translate("MainWindow", "Position"))
        self.NegX.setText(_translate("MainWindow", "←"))
        self.PosX.setText(_translate("MainWindow", "→"))
        self.PosY.setText(_translate("MainWindow", "↑"))
        self.NegY.setText(_translate("MainWindow", "↓"))
        self.PosFocus.setText(_translate("MainWindow", "↑"))
        self.NegFocus.setText(_translate("MainWindow", "↓"))
        self.StageMovementLb_2.setText(_translate("MainWindow", "Z-Focus"))
        self.StageMovementLb_3.setText(_translate("MainWindow", "Step (nm)"))
        self.Save.setText(QCoreApplication.translate("MainWindow", u"Save Meta", None))
        self.Wavelb.setText(_translate("MainWindow", "Wavelength"))
        self.YsizeLb.setText(_translate("MainWindow", "Y Size (um)"))
        self.Time_lb.setText(_translate("MainWindow", "Time (m.s)"))
        self.Milling_lb.setText(_translate("MainWindow", "Milling Rate (nm/s)"))
        self.GaussFit_lb.setText(_translate("MainWindow", "Guassian Fit"))
        self.sigmaX_lb.setText(_translate("MainWindow", "sigma_X"))
        self.A_lb.setText(_translate("MainWindow", "A"))
        self.X0_lb.setText(_translate("MainWindow", "X0"))
        self.Y0_lb.setText(_translate("MainWindow", "Y0"))
        self.C_lb.setText(_translate("MainWindow", "C"))
        self.Fit_Button.setText(_translate("MainWindow", "Fit"))
        self.PSF_X_Y.setText(_translate("MainWindow", "X/Y"))
        self.ExpFreq_lb.setText(_translate("MainWindow", "Exp Freq"))
        self.Begin_Fit.setText(_translate("MainWindow", "Begin Fit?"))
        self.Reset_Fit.setText(_translate("MainWindow", "Reset_Fit?"))
        self.AYlmLb.setText(_translate("MainWindow", "Y Lim Max"))
        self.AYMinlmLb.setText(_translate("MainWindow", "Y Lim Min"))