# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Andor_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
import pyqtgraph as pg
import numpy as np


class Ui_CapturedImage(object):
    imagedata = QtCore.pyqtSignal(str)
    def setupUi(self, CapturedImage, data):
        widget = QtWidgets.QWidget()
        CapturedImage.setObjectName("CapturedImage")
        CapturedImage.resize(984, 813)
        self.centralwidget = QtWidgets.QWidget(CapturedImage)
        self.centralwidget.setObjectName("centralwidget")
        self.CapturePlot = pg.ImageView()
        print(data.shape)
        self.CapturePlot.setImage(data)
        #self.Captured.setGeometry(QtCore.QRect(20, 10, 941, 771))
        #self.Captured.setObjectName("Captured")
        CapturedImage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CapturedImage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        CapturedImage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CapturedImage)
        self.statusbar.setObjectName("statusbar")
        CapturedImage.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(CapturedImage)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(CapturedImage)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        # color map

        # Creating a grid layout
        layout = QtWidgets.QGridLayout()

        # setting this layout to the widget
        widget.setLayout(layout)

        # plot window goes on right side, spanning 3 rows
        layout.addWidget(self.CapturePlot, 0, 1, 3, 1)

        # setting this widget as central widget of the main window
        CapturedImage.setCentralWidget(widget)
        self.retranslateUi(CapturedImage)
        QtCore.QMetaObject.connectSlotsByName(CapturedImage)

    def retranslateUi(self, CapturedImage):
        _translate = QtCore.QCoreApplication.translate
        CapturedImage.setWindowTitle(_translate("CapturedImage", "MainWindow"))
        self.menuFile.setTitle(_translate("CapturedImage", "File"))
        self.actionSave.setText(_translate("CapturedImage", "Save"))
        self.actionOpen.setText(_translate("CapturedImage", "Open"))

